name: gardenfth
description: A cross platform client for garden, a poultry ordering ecommerce service .

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.2
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.0.0
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.7
  algolia: ^0.1.6+1
  neumorphic: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  json_serializable: ^3.3.0


flutter:
  assets:
    - assets/images/

  uses-material-design: true
  fonts:
  - family: SFPROBOLD
    fonts:
      - asset: assets/fonts/sfprobold.ttf
  - family: SF-Pro
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Medium.ttf
      - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        weight: 700



